### ISSUE TITLE
Upgrade RESTEasy to 6.2.4.Final

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-spring#113]
Tag: https://github.com/resteasy/resteasy/releases/tag/6.2.4.Final

This also requires a bump to Servlet 6.0.

**Comment by liweinan** [comment]
This has been fixed in these commits: https://github.com/resteasy/resteasy-spring/commit/5e4d5116b7d60dfb22405eb47d1cea9ef6d0eddb ' https://github.com/resteasy/resteasy-spring/commit/c4e6d5046ec30711ef13f591f4700a7cd4e5f9bb

I plan to do a release next week.

**Comment by liweinan** [comment]
Included in: https://github.com/resteasy/resteasy-spring/releases/tag/3.0.3.Final
