### ISSUE TITLE
Split the feature pack

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-spring#12]
The `galleon-feature-pack` should be split into separate modules like WildFly's `ee-feature-pack`. The `galleon-feature-pack` should only have a `pom.xml` and the `wildfly-feature-pack-build.xml`. The modules and any tasks should be split out.

**Comment by jamezp** [comment]
I'm going to do the same think for resteasy-microprofile https://github.com/resteasy/resteasy-microprofile/issues/27 and likely RESTEasy itself. This can be done after the initial module PR, but we should likely do it before we do a 2.0.0.Final release.

**Comment by liweinan** [comment]
@jamezp I'll work on this.

**Comment by liweinan** [comment]
https://github.com/wildfly/wildfly/tree/main/ee-feature-pack

**Comment by liweinan** [comment]
duplicate with: https://github.com/resteasy/resteasy-spring/issues/48
