### ISSUE TITLE
The project cannot compile with `resteasy 6.1.0-SNAPSHOT` currently

### ISSUE THREAD

**Issue by liweinan** [resteasy/resteasy-spring#20]
I tried to compile the project locally with `resteasy 6.1.0-SNAPSHOT` but failed:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/201907/159474093-31499ddd-8de9-4017-a0b3-20e86e0322df.png">

@jamezp It seems related with some SeBootstrap APIs are not found. I guess it's because of the jakarata API version I used is not correct. Could you please help to check this when you have time? Thanks!

**Comment by jamezp** [comment]
Yes. RESTEasy 6.1.0 will only work with Jakarta REST 3.1.

**Comment by liweinan** [comment]
@jamezp Okay! Let me try with REST 3.1

**Comment by liweinan** [comment]
@jamezp After upgrading the Jakarta REST to `3.1` the upgrade passed locally. Thanks for teaching!

I'll wait for formal release of RESTEasy `6.1.0` and do the relative release here.

**Comment by jamezp** [comment]
Is Spring planning on support Jakarta REST 3.0 or Jakarta REST 3.1? We may need to consider that here.

**Comment by liweinan** [comment]
@jamezp I'll make progress on this let you know my findings.
