### ISSUE TITLE
Enable the SpringMvcHttpResponseCodesTest once the RESTEasy 6.2.8.Final upgrade is done

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-spring#248]
Currently the `SpringMvcHttpResponseCodesTest` does not work with JUnit 5 due to WildFly Creaper being used in RESTEasy 6.2.x. This is resolved by https://github.com/resteasy/resteasy/pull/4047, however it requires a new release of RESTEasy.

**Comment by liweinan** [comment]
I'll start to work on this.
